apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mutating-webhook.fullname" . }}
  labels:
    {{- include "mutating-webhook.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mutating-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mutating-webhook.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mutating-webhook.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: https
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: https
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: {{ include "mutating-webhook.fullname" . }}-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
