apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodejs.fullname" . }}
  labels:
{{ include "nodejs.labels" . | indent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePort)) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- else if eq .Values.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "nodejs.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
